# Generated by Django 6.0.6 on 2026-06-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesection', '0002_slider_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
