# Generated by Django 6.0.6 on 2026-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dialogue_image/')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('venue', models.CharField(blank=True, max_length=250, null=True)),
                ('organized_by', models.CharField(blank=True, max_length=250, null=True)),
                ('chairperson', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('chief_guest', models.CharField(blank=True, max_length=250, null=True)),
                ('program_schedule', models.JSONField(default=list)),
                ('sessions', models.JSONField(default=list)),
                ('videos', models.JSONField(default=list)),
                ('past_event', models.JSONField(default=dict)),
            ],
        ),
    ]
