# Generated by Django 6.0.6 on 2026-06-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='past_event',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='program_schedule',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='videos',
        ),
    ]
