# Generated by Django 6.0.6 on 2026-06-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_othersite_programschedule_session_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('participants', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('current', 'Current'), ('upcoming', 'Upcoming')], default='upcoming')),
            ],
        ),
    ]
