# Generated by Django 6.0.6 on 2026-07-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_programhighlight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programhighlight",
            name="text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
