# Generated by Django 6.0.6 on 2026-07-05 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HighlightSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("tagline", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "button_text",
                    models.CharField(default="View Event Page", max_length=100),
                ),
                ("button_url", models.URLField(blank=True)),
                ("slide_image_1", models.ImageField(upload_to="highlights/")),
                ("slide_image_2", models.ImageField(upload_to="highlights/")),
                ("slide_image_3", models.ImageField(upload_to="highlights/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Highlight Section",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="sessions/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "highlight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="home_section.highlightsection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
