# Generated by Django 6.0.6 on 2026-06-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to='books/pdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/image'),
        ),
        migrations.AlterField(
            model_name='gloabalpower',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='global/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/'),
        ),
        migrations.AlterField(
            model_name='researchartical',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchartical',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Artical/file'),
        ),
    ]
